# Generated by Django 2.2.7 on 2019-11-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
