# Generated by Django 2.2.7 on 2019-11-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0006_auto_20191130_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='location',
            field=models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='other_activities',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
