# Generated by Django 2.2.7 on 2019-12-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0013_auto_20191205_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='unique_squirrel_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
